name: ci

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  pull_request:

# Cancel previous PR builds.
concurrency:
  # Cancel all workflow runs except latest within a concurrency group. This is achieved by defining a concurrency group for the PR.
  # Non-PR builds have singleton concurrency groups.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-success:
    if: ${{ !success() }}
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - run: false

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version:
          - 17
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-mvn-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os}}-mvn-
      - name: Maven install
        run: ./mvnw install -T 1C -B -V -P ci -DskipTests
      - name: Maven test
        run: ./mvnw test -T 1C -B -P ci
